In [3]:
import numpy as np
import math 
beta = 1+0.15*(51-51)
e = 0.005

In [10]:
A = np.array([[9.7,          -1.0,        2.0,          3.0  ],
             [-1.0,          9.7,       3.0,         2.0  ],
             [2.0,          3.0,        9.7,         1.0  ],
             [3.0,           2.0,       1.0,          9.7  ]])
print("A:\n", A)

A:
 [[ 9.7 -1.   2.   3. ]
 [-1.   9.7  3.   2. ]
 [ 2.   3.   9.7  1. ]
 [ 3.   2.   1.   9.7]]


In [11]:
def return_max(A):
    max_  = -100
    row = -1
    col = -1
    for i in range(0, 4):
        for j in range(0, 4):
            if i < j:
                if abs(A[i][j]) > max_:
                    max_ = abs(A[i][j])
                    row = i
                    col = j
    return row, col, max_

In [12]:
def arcctg(x):
    if x == 0:
        return np.pi/2
    return np.arctan(1/x)

In [15]:
A_array = [A]
Q_array = []
for i in range(8):
    diag_elem = np.diagonal(A_array[i])
    n, m, max_= return_max(A_array[i])
    if max_ < e:
        print("max < e")
        break
    print("max =", max_, "i, j =", n, m)
    phi = 1/2 * (math.pi/2 - math.atan((A_array[i][n, n] - A_array[i][m, m])/(2 * A_array[i][n, m])))
    print("Phi =", phi)
    sin = np.sin(phi)
    cos = np.cos(phi)
    Q = np.eye(4)
    Q[n, n] = cos
    Q[n, m] = -sin
    Q[m, n] = sin
    Q[m, m] = cos
    Q_array.append(Q)
    print("cos = ", cos)
    print("sin = ", sin)
    print("Q:\n", Q)
    QT = np.transpose(Q)
    print("Q транспонированная:\n", QT)
    temp = QT.dot(A_array[i])
    temp2 = temp.dot(Q)
    A_array.append(temp2)
    print("A[", i + 1, "]:\n", np.around(A_array[i+1], decimals = 25), sep="")
    print("A[", i + 1, "]:\n", A_array[i+1], sep="")

max = 3.0 i, j = 0 3
Phi = 0.7853981633974483
cos =  0.7071067811865476
sin =  0.7071067811865476
Q:
 [[ 0.70710678  0.          0.         -0.70710678]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.70710678  0.          0.          0.70710678]]
Q транспонированная:
 [[ 0.70710678  0.          0.          0.70710678]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [-0.70710678  0.          0.          0.70710678]]
A[1]:
[[12.7         0.70710678  2.12132034  0.        ]
 [ 0.70710678  9.7         3.          2.12132034]
 [ 2.12132034  3.          9.7        -0.70710678]
 [ 0.          2.12132034 -0.70710678  6.7       ]]
A[1]:
[[12.7         0.70710678  2.12132034  0.        ]
 [ 0.70710678  9.7         3.          2.12132034]
 [ 2.12132034  3.          9.7        -0.70710678]
 [ 0.          2.12132034 -0.70710678  6.7       ]]
max = 3.0 i, j = 1 2
Phi = 0.785398163397448

In [13]:
def Jacobi(A0, eps):
    Q_Res = np.eye(4)
    k=0
    row, col, max_e = return_max(A0)
    while max_e > eps:
        phi = 1/2 * arcctg((A0[col][col] - A0[row][row])/(2 * A0[col][row]))
        Q = np.eye(4)
        Q[col][col] = np.cos(phi)
        Q[col][row] = -np.sin(phi)
        Q[row][col] = np.sin(phi)
        Q[row][row] = np.cos(phi)
        A0 = Q.T.dot(A0).dot(Q)
        row, col, max_e = return_max(A0)
        Q_Res = Q_Res.dot(Q)
        k += 1
        print("k=", k, "\n", "Q_k = ", Q, "\n\n", "Ak = ", A0, "\n\n")
    return A0, Q_Res

In [14]:
Ak, Q_Res = Jacobi(A, e)

k= 1 
 Q_k =  [[ 0.70710678  0.          0.          0.70710678]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [-0.70710678  0.          0.          0.70710678]] 

 Ak =  [[ 6.7        -2.12132034  0.70710678  0.        ]
 [-2.12132034  9.7         3.          0.70710678]
 [ 0.70710678  3.          9.7         2.12132034]
 [ 0.          0.70710678  2.12132034 12.7       ]] 


k= 2 
 Q_k =  [[ 1.          0.          0.          0.        ]
 [ 0.          0.70710678  0.70710678  0.        ]
 [ 0.         -0.70710678  0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]] 

 Ak =  [[ 6.7 -2.  -1.   0. ]
 [-2.   6.7  0.  -1. ]
 [-1.   0.  12.7  2. ]
 [ 0.  -1.   2.  12.7]] 


k= 3 
 Q_k =  [[ 0.70710678  0.70710678  0.          0.        ]
 [-0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]] 

 Ak =  [[ 8.7      

In [9]:
Spr_A = Ak.diagonal()
print("Spr(A):", Spr_A)
print("Q", Q_Res)

Spr(A): [ 5.52786405  7.17157288 12.82842712 14.47213595]
Q [[ 0.37174803  0.65328148 -0.27059805  0.60150096]
 [-0.60150096  0.27059805  0.65328148  0.37174803]
 [ 0.37174803 -0.65328148  0.27059805  0.60150096]
 [-0.60150096 -0.27059805 -0.65328148  0.37174803]]


In [126]:
Q = np.transpose(Q_Res)
for i in range(4):
    print("i=", i)
    print("q=", Q[i])
    print("A*q=", A.dot(Q[i]))
    print("lambda * q=", Spr_A[i] * Q_[i])

i= 0
q= [ 0.37174803 -0.60150096  0.37174803 -0.60150096]
A*q= [ 2.05497259 -3.3250155   2.05497259 -3.3250155 ]
lambda * q= [ 3.74107189 -3.74107189 -1.13270543 -1.13270543]
i= 1
q= [ 0.65328148  0.27059805 -0.65328148 -0.27059805]
A*q= [ 4.68505576  1.94061364 -4.68505576 -1.94061364]
lambda * q= [-1.46951507  1.46951507 -4.85347857 -4.85347857]
i= 2
q= [-0.27059805  0.65328148  0.27059805 -0.65328148]
A*q= [-3.47134737  8.38057389  3.47134737 -8.38057389]
lambda * q= [ 2.62865166  2.62865166  8.68184667 -8.68184667]
i= 3
q= [0.60150096 0.37174803 0.60150096 0.37174803]
A*q= [8.7050036 5.3799881 8.7050036 5.3799881]
lambda * q= [ 9.79425336  9.79425336 -2.96546131  2.96546131]
