In [1]:
import numpy as np
import matplotlib as plt

## Метод Якоби

In [75]:
A = []
A.append(np.array (
[[10, -1, 2, 3 ],
 [-1, 10, 3, 2 ],
 [2, 3,  10, -1 ],
 [3,  2,  -1, 10]]
))

a - alpha

b - betta

In [76]:
a = b = 0

In [77]:
def findMax(M):
    AmaxEl = 0
    for i in range(0, 4):
        for j in range(i, 4):
            if ((i != j) & (abs(M[i][j]) >= AmaxEl)):
                AmaxEl = abs(M[i][j])
                m = i
                n = j
    return m, n

In [78]:
a, b = findMax(A[0])
a, b

(1, 2)

In [79]:
phi = .5 * (np.pi/2 - np.arctan(((A[0])[a][a]-(A[0])[b][b])/(2*(A[0])[a][b])))
phi

0.7853981633974483

In [80]:
Q = []
Q.append(np.eye(4, 4))
(Q[0])[a][a] = np.cos(phi)
(Q[0])[a][b] = - np.sin(phi)
(Q[0])[b][a] = np.sin(phi)
(Q[0])[b][b] = np.cos(phi)
print("Q:\n", Q[0])
print("Q транспонированная:\n", Q[0].T)

Q:
 [[ 1.          0.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678  0.        ]
 [ 0.          0.70710678  0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]]
Q транспонированная:
 [[ 1.          0.          0.          0.        ]
 [ 0.          0.70710678  0.70710678  0.        ]
 [ 0.         -0.70710678  0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]]


In [81]:
A.append(Q[0].transpose().dot(A[0]).dot(Q[0]))
print("A[1]:\n", A[1])

A[1]:
 [[10.          0.70710678  2.12132034  3.        ]
 [ 0.70710678 13.          0.          0.70710678]
 [ 2.12132034  0.          7.         -2.12132034]
 [ 3.          0.70710678 -2.12132034 10.        ]]


Первый элемент посчитан, теперь идем в цикл для всех остальных

In [82]:
eps = .005
k = 1

In [83]:
def acot(x):
    if x == 0:
        return np.pi/2
    return np.arctan(1/x)


In [84]:
a, b = findMax(A[k])

while abs((A[k])[a][b]) >= eps:
    phi = .5*acot(((A[k])[a][a]-(A[k])[b][b])/(2*(A[k])[a][b]))
    
    Q.append(np.eye(4, 4))
    (Q[k])[a][a] = np.cos(phi)
    (Q[k])[a][b] = - np.sin(phi)
    (Q[k])[b][a] = np.sin(phi)
    (Q[k])[b][b] = np.cos(phi)
    
    A.append(Q[k].transpose().dot(A[k]).dot(Q[k]))
    k += 1
    a, b = findMax(A[k])

A[k]

array([[14.,  0.,  0.,  0.],
       [ 0., 12.,  0.,  0.],
       [ 0.,  0.,  4.,  0.],
       [ 0.,  0.,  0., 10.]])

7

Проверка

In [85]:
m_Q = np.eye(4, 4)
for i in range(0, k):
    m_Q = m_Q.dot(Q[i])
m_Q

array([[ 0.5, -0.5, -0.5, -0.5],
       [ 0.5,  0.5, -0.5,  0.5],
       [ 0.5,  0.5,  0.5, -0.5],
       [ 0.5, -0.5,  0.5,  0.5]])

In [86]:
q1 = np.array([m_Q[0][0], m_Q[0][1], m_Q[0][2], m_Q[0][3]])
q2 = np.array([m_Q[1][0], m_Q[1][1], m_Q[1][2], m_Q[1][3]])
q3 = np.array([m_Q[2][0], m_Q[2][1], m_Q[2][2], m_Q[2][3]])
q4 = np.array([m_Q[3][0], m_Q[3][1], m_Q[3][2], m_Q[3][3]])

m_q = m_Q.transpose()

In [87]:
lam = [(A[k])[0][0], (A[k])[1][1], (A[k])[2][2], (A[k])[3][3]]
lam

[14.000000000000004, 12.000000000000002, 4.000000000000001, 10.000000000000002]

In [88]:
for i in range(0, 4):
    print("", A[0].dot(m_q[i]), "\n", lam[i]*m_q[i], end="\n\n")

 [7. 7. 7. 7.] 
 [7. 7. 7. 7.]

 [-6.  6.  6. -6.] 
 [-6.  6.  6. -6.]

 [-2. -2.  2.  2.] 
 [-2. -2.  2.  2.]

 [-5.  5. -5.  5.] 
 [-5.  5. -5.  5.]



In [89]:
wa, va = np.linalg.eigh(A[0])
wa

array([ 4., 10., 12., 14.])